services:
  auth:
    build:
      context: ../auth
      args:
        PORT: 3005
    volumes:
      - ../auth/src:/app/src
      - ../auth/public:/app/public
      #- auth-node-modules:/app/node_modules
    ports:
      - "3005:3005"
    networks:
      - cortex-bank-network
    environment:
      - PORT=3005
      - ENABLE_HOT_RELOAD=true
      - CHOKIDAR_USEPOLLING=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3005"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 300s

  navigation-drawer:
    build:
      context: ../navigation-drawer
    volumes:
      - ../navigation-drawer/src:/app/src
      - ../navigation-drawer/public:/app/public
      #- navigation-drawer-node-modules:/app/node_modules
    ports:
      - "3001:3001"
    networks:
      - cortex-bank-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 300s

  dashboard:
    build:
      context: ../dashboard
    volumes:
      - ../dashboard/src:/app/src
      - ../dashboard/public:/app/public
      #- dashboard-node-modules:/app/node_modules
    ports:
      - "3002:3002"
    networks:
      - cortex-bank-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 300s

  transactions:
    build:
      context: ../transactions
    volumes:
      - ../transactions/src:/app/src
      - ../transactions/public:/app/public
      #- transactions-node-modules:/app/node_modules
    ports:
      - "3003:3003"
    networks:
      - cortex-bank-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3003"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 300s

  statement:
    build:
      context: ../statement
    volumes:
      - ../statement/src:/app/src
      - ../statement/public:/app/public
      #- statement-node-modules:/app/node_modules
    ports:
      - "3004:3004"
    networks:
      - cortex-bank-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3004"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 300s

  root-config:
    build:
      context: .
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      #- root-config-node-modules:/app/node_modules
    ports:
      - "3000:3000"
    networks:
      - cortex-bank-network
    depends_on:
      auth:
        condition: service_healthy
      navigation-drawer:
        condition: service_healthy
      dashboard:
        condition: service_healthy
      transactions:
        condition: service_healthy
      statement:
        condition: service_healthy

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:3000"
    environment:
      MONGO_URI: mongodb://mongo:27017/app
    depends_on:
      - mongo
    networks:
      - cortex-bank-network

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - cortex-bank-network

networks:
  cortex-bank-network:
    driver: bridge

volumes:
  #auth-node-modules:
  #navigation-drawer-node-modules:
  #dashboard-node-modules:
  #transactions-node-modules:
  #statement-node-modules:
  #root-config-node-modules:
  mongo_data:
